// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gorhvosaapmqadktjbvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdvcmh2b3NhYXBtcWFka3RqYnZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDQ4MTEsImV4cCI6MjA2NTUyMDgxMX0.LkVgo9727_TntgUqSPwyrzfuaU07pMgeUVrLeseBWkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);